### ISSUE TITLE
[Fix]: Feedback 관련 오류

### ISSUE THREAD

**Issue by Jeong-Junhwan** [boostcampaitech4lv23recsys1/final-project-level3-recsys-01#102]
![image](https://user-images.githubusercontent.com/64895794/217284401-7ff8501f-e313-4d2b-927d-3ff51c0a7f6d.png)
백에서 받는 정보는 이런 꼴 근데 프론트는 아래와 같이 보내고 있음.

옛날에는 없던 오류라서 언젠가 프론트 쪽 로직이 바뀐 것 같다. 

![image](https://user-images.githubusercontent.com/64895794/217284647-58c11578-53f4-48ef-930a-ce5a3b6878eb.png)

**Comment by kimeunh3** [comment]
해결 #105
