### ISSUE TITLE
[Feat]: 아이템이 다 채워져 있는 상태에서는 코디추천 버튼 비활성화 하기

### ISSUE THREAD

**Issue by kimeunh3** [boostcampaitech4lv23recsys1/final-project-level3-recsys-01#108]
아래와 같이 한벌옷의 경우는 하의가 채워져 있지 않더라도 비활성화 시켜야함!

![image](https://user-images.githubusercontent.com/59808674/217443277-a111e8e2-dace-455a-8bfa-2b014e35fd9d.png)

**Comment by 41ow1ives** [comment]
#111
