### ISSUE TITLE
[Fix]: 코디 진단에서 아이템 선택 후 부분 리셋을 모두 눌렀을 때 코디 진단 비활성화

### ISSUE THREAD

**Issue by kimeunh3** [boostcampaitech4lv23recsys1/final-project-level3-recsys-01#109]
코디 진단에서 아이템 선택 후 부분 리셋을 모두 눌렀을 때 코디 진단버튼이 비활성화 되어야 하는데 안되고 있다! 

![image](https://user-images.githubusercontent.com/59808674/217445959-a8a237e6-02c1-4405-8c90-2cfe01193037.png)

**Comment by 41ow1ives** [comment]
#111
