### ISSUE TITLE
[Fix]: 코디 추천 2? 3?가지 선택 오류

### ISSUE THREAD

**Issue by Jeong-Junhwan** [boostcampaitech4lv23recsys1/final-project-level3-recsys-01#113]
현재 코디 추천은 적어도 2개? 3개? 이상의 코디를 선택해야만 돌아가도록 설정되어있습니다. 

그런데 코디 진단에서 코디 추천으로 넘어 간 경우 문제가 발생해요
![image](https://user-images.githubusercontent.com/64895794/217550815-d8c441db-d0a1-44af-ba40-32673ebafe15.png)

여기서 추천으로 넘어가면 2가지가 선택되어 있기 때문에, 바로 추천이 가능해야 합니다. 
![image](https://user-images.githubusercontent.com/64895794/217550992-0ccbc746-73b7-4f16-9e1d-cc2b021fe088.png)

그런데 이렇게 버튼이 비활성화 되어 있어요 여기서 2개를 새로 눌러줘야 버튼이 눌러집니다. 

---

제 생각에 누르는 횟수를 카운트 하나 싶어서 다른 테스트를 진행해봤습니다. 

![image](https://user-images.githubusercontent.com/64895794/217551649-e6319612-afdc-4f86-9360-feacffce6c05.png)

모자만 냅다 3번 선택한 경우에도 추천 버튼이 활성화가 되는 것을 확인했습니다.

**Comment by 41ow1ives** [comment]
- numberState를 CDP랑 PRP가 공유하지 않아서 생기는 문제 -> 해결중
